name: Compilar y Desplegar
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    env: 
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.2.0
        with: 
          dotnet-version: 8.0.x
      
      - name: Dependencies Fetching
        run: dotnet restore
      
      - name: Building
        run: dotnet build --no-restore
      
      - name: Testing
        run: dotnet test --no-build
      
      - name: Publish
        run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: ./miapp
          name: build
        
